name: 'docs'
on:
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Terraform Docs
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          output-file: README.md
          output-method: inject
          git-push: "true"
