# Regarding bumping the tags of the project, it will be done via commit messages containing
# #major, #minor or #patch  string in the commit msg. Read more below.
# Automatic Bumping: If no #major, #minor or #patch tag is contained in the merge commit message,
# it will bump whichever DEFAULT_BUMP is set to (which is minor by default).
# Disable this by setting DEFAULT_BUMP to none. https://github.com/anothrNick/github-tag-action

name: 'tag'
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Tag'
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: none
